/*
 * generated by Xtext 2.22.0
 */
package info.scce.cinco.fp.compdsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class ComponentDslStandaloneSetup extends ComponentDslStandaloneSetupGenerated {

	def static void doSetup() {
		new ComponentDslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
