/*
 * generated by Xtext 2.22.0
 */
package info.scce.cinco.fp.compdsl


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class ComponentDslRuntimeModule extends AbstractComponentDslRuntimeModule {
	
	
	
	
}
